# This file shows examples of cert-manager resources to get a
# cert from Let's Encrypt using the HTTP01 solver.

# Create a production ClusterIssuer. Remember: with Let's Encrypt it is
# critical to test your configuration against their staging server first! It's
# far too easy to go over the production rate limit with a failing
# configuration and get stuck.
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
 name: letsencrypt-production
 namespace: cert-manager
spec:
 acme:
   email: "<DEMO_EMAIL>"
   server: "https://acme-v02.api.letsencrypt.org/directory"
   privateKeySecretRef:
     name: le-production-issuer-account-key
   solvers:
     - http01:
         ingress:
           class: 'nginx'

# Given a production ClusterIssuer, use it to create the production cert for
# Emissary-ingress.
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
 name: faces-production
 namespace: emissary
spec:
 secretName: faces-demo-cert
 duration: 2160h
 renewBefore: 360h
 dnsNames:
 - <DEMO_HOST>
 issuerRef:
   name: letsencrypt-production
   kind: ClusterIssuer
