---
apiVersion: linkerd.io/v1alpha2
kind: ServiceProfile
metadata:
  creationTimestamp: null
  name: color.faces.svc.cluster.local
  namespace: faces
spec:
  routes:
  - condition:
      method: GET
      pathRegex: /
    name: GET /
