apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: public-ca-bundle
  namespace: faces

spec:
  sources:
  - useDefaultCAs: true

  target:
    configMap:
      key: "cacert.pem"

    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: faces
